### ISSUE TITLE
No index.js file inside lib folder of newly created biojs package

### ISSUE THREAD

**Issue by DevasenaInupakutika** [biojs/edu#21]
I was following tutorial on package basics `http://edu.biojs.net/series/101/30_package_basics.html#` and under step 5 i.e. `Start Coding` section, I couldn't find `index.js` under `lib` folder of my package. 

Instead it's present in initial project directory that I created. 

Is this `index.js` file same as `<module-name.js>` file under `lib` folder or `index.js` in project folder?

Seems like it should be `<modulename.js>` file under `lib` folder under project directory.

**Comment by greenify** [comment]
Slush should create a lib/index.js file - of not please reopen ;-)
