### ISSUE TITLE
Highlight links in the navigation side bar more prominently

### ISSUE THREAD

**Issue by jessica-jordan** [biojs/edu#53]
Active chapter links in the navigation side bar have the same color as chapter headlines and can be overlooked now easily. Please highlight the links that are currently active more prominently. e.g. use green color to make them stand out:

color: #4ca33a;

**Comment by jajodiaraghav** [comment]
I wonder why this issue is still open. Is there something else that can be done here?
Thanks in advance

**Comment by wilzbach** [comment]
> I wonder why this issue is still open. Is there something else that can be done here?

I guess nobody closed it. Thanks for the ping!
